import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

      <nav className="flex justify-between px-20 py-4 items-center bg-gradient-to-r from-black from-20% to-25% to-[#f94bad]">
        <div className='italic'>
          <a href='#'>
          <div className='flex'>
            <h1 className="text-5xl text-[#f94bad] font-semibold">Angel
            </h1>
            <div className='place-self-center w-full h-full'>
            <svg width="50x" height="50px" viewBox="0 0 1024 1024" class="ml-2" version="1.1" xmlns="http://www.w3.org/2000/svg" fill="#000000"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path d="M927.4 273.5v-95.4h-87.9V82.8h-201v95.3h-87.9v95.4h-78.5v-95.4h-88V82.8H183.2v95.3H95.3v95.4H16.7v190.6h78.6v95.4h75.3v95.3H246v95.3h87.9v95.4h100.5v95.3h153.9v-95.3h100.4v-95.4h88v-95.3H852.1v-95.3h75.3v-95.4h78.5V273.5z" fill="#f94bad"></path></g></svg>
            </div>
          </div>
        <h1 className="text-xl text-[#2bd9ff] font-medium">Internet Yamero</h1>
          </a>
        </div>
        <div className="flex items-center">
          <ul className="flex items-center space-x-4">
            <a href='#'>
            <li className="font-semibold text-white hover:bg-white hover:text-[#2bd9ff] duration-200 rounded-xl py-8 px-2">KwaiiAngel</li>
            </a>
            <a href='#'>
            <li className="font-semibold text-white hover:bg-black hover:text-red-500 duration-200 rounded-xl py-8 px-2">AmeChan</li>
            </a>
            <li>
              <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path d="M12 14l9-5-9-5-9 5 9 5z" />
                <path d="M12 14l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14z" />
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 14l9-5-9-5-9 5 9 5zm0 0l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14zm-4 6v-7.5l4-2.222" />
              </svg>
            </li>
            <li>
              <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
              </svg>
            </li>
          </ul>
        </div>
      </nav>
        {children}
        
      </body>
    </html>
  )
}
